apiVersion: apps/v1
kind: Deployment
metadata:
  name: pv-forecast
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pv
  template:
    metadata:
      labels:
        app: pv
    spec:
      containers:
      - name: pv
        image: yourdocker/pv-forecast:latest
        ports:
        - containerPort: 8501
