apiVersion: v1
kind: Service
metadata:
  name: pv-forecasting-service
spec:
  selector:
    app: pv-forecasting
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8501
